version: '2'
services:
  solr:
    image: mossiso/womensbios:solr
    container_name: womensbios_solr
    restart: always
    ports:
     - ${SOLR_PORTS}
  womenbios:
    # Uncomment for development. Requires the Dockerfile to exist.
    #build: 
    #  context: .
    image: mossiso/womensbios:static
    container_name: womensbios_static
    depends_on:
      - solr
    ports:
      - ${PORTS}
    restart: always
    # Uncomment for development. Requires an existing static-content
    # folder with all the static files.
    #volumes:
    #  - ./static-content:/usr/share/nginx/html
