version: '2'
services:
  solr:
    image: scholarslab/wbsolr:1.0
    container_name: womensbios_solr
    restart: always
    ports:
     - "8983:8983"
  womenbios:
    build: 
      context: .
    image: scholarslab/womensbios:1.0
    container_name: womensbios_static
    depends_on:
      - solr
    ports:
      - "80:80"
    restart: always
    # Uncomment only when developing, requires an existing static-content folder with all the static files
    #volumes:
    #  - ./static-content:/usr/share/nginx/html
