version: '2'
services:
  wbi_solr:
    image: solr:7
    container_name: wbi_solr
    restart: always
    volumes:
      - ./web.xml:/opt/solr/web.xml
      - ./managed-schema:/opt/solr/managed-schema
      - ./load-data:/opt/docker-solr/scripts/load-data
      - ./alldata.json:/opt/solr/datafile.json
      - ./solr.in.sh:/opt/solr/solr.in.sh
    entrypoint:
      - docker-entrypoint.sh
      - load-data
      - wbcore
    expose:
      - "8983"
    labels:
      - "traefik.enable=false"

  wbi_static:
    image: nginx
    container_name: wbi_static
    depends_on:
      - wbi_solr
    restart: always
    volumes:
      - ./static-content:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=thenetwork"
      - "traefik.port=80"
      - "traefik.backend=wbi_static"
      - "traefik.frontend.rule=Host:womensbios.lib.virginia.edu"

networks:
  default:
    external:
      name: thenetwork
