version: '2'
services:
  solr:
    image: registry.gitlab.com/scholars-lab/womensbios/wb-solr:1.0
    container_name: womensbios_solr
    restart: always
    ports:
     - ${SOLR_PORTS}
  womenbios:
    # Uncomment for development. Requires the Dockerfile to exist.
    build: 
      context: .
    image: registry.gitlab.com/scholars-lab/womensbios/wb-static:1.1
    container_name: womensbios_static
    depends_on:
      - solr
    ports:
      - ${PORTS}
    restart: always
    # Uncomment for development. Requires an existing static-content
    # folder with all the static files.
    volumes:
      - ./static-content:/usr/share/nginx/html
